name: CD to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      # This is just so Actions has your code, not for EC2
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/fs-healthcare-dashboard || exit 1

            echo "Pulling latest code from GitHub..."
            git fetch origin master
            git reset --hard origin/master

            echo "Stopping old container (if any)..."
            docker stop healthcare || true
            docker rm healthcare || true

            echo "Building new Docker image..."
            docker build -t healthcare-backend .

            echo "Starting new container..."
            docker run -d \
              --name healthcare \
              --env-file .env \
              -p 8000:8000 \
              healthcare-backend

            echo "Deployment complete.